import { useState } from 'react'
import './App.css'

type Lang = 'it' | 'en'
type Copy = { it: string; en: string }
type ExperienceItem = { years: string; role: Copy; org: string; text: Copy }
type DiaryItem = { image: string; title: Copy; text: Copy }
type PublicationItem = { group: '01' | '02' | '03'; year: string; title: string; source: string; cover?: string }
type VideoItem = { id: string; title: Copy; caption: Copy }
type EducationItem = { years: string; title: Copy; org: Copy; detail: Copy }

function VideoPlayer({ id, title }: { id: string; title: string }) {
  const [playing, setPlaying] = useState(false)
  return playing
    ? <div className="video-player"><iframe src={`https://www.youtube-nocookie.com/embed/${id}?autoplay=1`} title={title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/></div>
    : <button type="button" className="video-player" aria-label={title} onClick={() => setPlaying(true)}>
        <img src={`https://img.youtube.com/vi/${id}/hqdefault.jpg`} alt={title} loading="lazy"/>
        <span className="play-btn"><span/></span>
      </button>
}

function Portrait() {
  const [broken, setBroken] = useState(false)
  return <figure className="hero-portrait">
    {broken
      ? <p className="placeholder">RITRATTO<br/>in attesa del file ritratto.webp</p>
      : <img src="./images/ritratto.webp" alt="Giorgio Micolitti" onError={() => setBroken(true)}/>}
  </figure>
}

const profile: Copy[] = [
  { it: 'Ingegnere Civile e Project & Construction Manager con oltre 24 anni di esperienza nella progettazione e realizzazione di infrastrutture civili di trasporto, pilota UAV certificato EASA A1/A2/A3. Ha maturato la propria esperienza nella Direzione Investimenti, nella Direzione Tecnica e nella Direzione Centrale Strategie e Pianificazione di Ferrovie dello Stato Italiane, per poi ricoprire per 11 anni ruoli di responsabilità crescente nella Direzione Operativa Territoriale di Roma di RFI. Attualmente è Responsabile della Struttura di Ingegneria dei Collegamenti Ferroviari di Stretto di Messina S.p.A.', en: 'Civil Engineer and Project & Construction Manager with more than 24 years of experience in the design and delivery of civil transport infrastructure, and an EASA A1/A2/A3 certified UAV pilot. His career has included FS Italiane Investment, Technical and Central Strategy & Planning directorates, followed by 11 years of progressively senior responsibilities within RFI Rome Territorial Operations. He is currently Head of Railway Connections Engineering at Stretto di Messina S.p.A.' },
  { it: 'Specializzato in infrastrutture ferroviarie civili — con particolare focus su ponti, gallerie e armamento — valutazione della redditività degli investimenti, standardizzazione tecnica con autorità nazionali ed europee, gestione di sito e HSE, due diligence, nuove costruzioni e realizzazione di stazioni. Esperienza consolidata anche in impianti tecnologici speciali, sostenibilità, mitigazione sismica e acustica, risk analysis e ottimizzazione dei consumi energetici.', en: 'Specialised in civil railway infrastructure — particularly bridges, tunnels and trackwork — investment profitability assessment, technical standardisation with national and European authorities, site and HSE management, due diligence, new construction and station delivery. Additional experience includes special technological systems, sustainability, seismic and acoustic mitigation, risk analysis and energy optimisation.' },
  { it: 'A livello internazionale è stato membro di numerosi gruppi di lavoro presso le principali istituzioni europee di settore (UIC, AEIF, CER, EU-FIT) e ha collaborato con le principali partecipate RFI in ambito gallerie transfrontaliere (Brenner Basis Tunnel e Torino–Lione). In FS Italiane ha affiancato a queste competenze la definizione di strategie industriali e di mercato di Gruppo, occupandosi per diversi anni della pianificazione e del monitoraggio dei KPI per lo sviluppo strategico del business immobiliare e di trasporto.', en: 'Internationally, he served in working groups at major European rail-sector institutions (UIC, AEIF, CER, EU-FIT) and collaborated on the Brenner Base Tunnel and Turin–Lyon cross-border tunnel programmes. At FS Italiane he also worked on Group industrial and market strategy, planning and monitoring KPIs for real-estate and transport business development.' },
  { it: "Le competenze manageriali trasversali sono state sviluppate attraverso un Executive Master in General Management e consolidate all'interno della Direzione Strategie di Ferrovie dello Stato Italiane S.p.A., con impatto diretto sulla pianificazione industriale del Gruppo FS: individuazione e reportistica dei rischi, proposta di soluzioni a supporto del Direttore Strategie di Gruppo.", en: 'Cross-functional management skills were developed through an Executive Master in General Management and consolidated within FS Italiane Strategy Directorate, contributing directly to Group industrial planning through risk identification, reporting and the development of solutions in support of the Group Strategy Director.' },
  { it: "Conoscenza completa dell'intero processo realizzativo — dall'ideazione al completamento del progetto — con capacità di selezionare efficacemente le risorse operative e allineare i processi di pianificazione e budgeting. Ruolo di collegamento, guida e motivazione per team, consulenti, enti locali, subappaltatori e clienti, per la consegna dei progetti nei tempi, nel budget e secondo i più elevati standard qualitativi. Esperienza nella gestione di team eterogenei, con supervisione diretta fino a circa 100 persone in cinque dipartimenti.", en: 'Complete knowledge of the delivery process — from concept to completion — with the ability to select operational resources and align planning and budgeting processes. A connecting, leadership and motivational role across teams, consultants, local authorities, subcontractors and clients, supporting delivery on time, within budget and to high quality standards. Experience managing heterogeneous teams, with direct supervision of up to approximately 100 people across five departments.' },
  { it: 'Docente di Tecnica dei Cantieri Infrastrutturali presso il Master Sapienza in Ingegneria delle Infrastrutture e dei Sistemi Ferroviari (IIS), edizioni 2020, 2021 e 2022.', en: 'Lecturer in Infrastructure Construction Site Techniques within Sapienza University Master in Infrastructure and Railway Systems Engineering (IIS), editions 2020, 2021 and 2022.' },
]

const experience: ExperienceItem[] = [
  { years: 'Nov 2023 — Presente', role: { it: 'Responsabile Ingegneria Collegamenti Ferroviari', en: 'Head of Railway Connections Engineering' }, org: 'Stretto di Messina S.p.A. · Roma', text: { it: 'Guida la Struttura Organizzativa “Ingegneria Collegamenti Ferroviari” di Stretto di Messina S.p.A.', en: 'Leads the Railway Connections Engineering organisational unit at Stretto di Messina S.p.A.' } },
  { years: 'Dic 2017 — Set 2023', role: { it: 'Responsabile Ingegneria Civile, Armamento, Patrimonio e Autorizzazioni, Ponti e Verifiche', en: 'Head of Civil Engineering, Trackwork, Property & Authorisations, Bridges & Inspections' }, org: 'RFI S.p.A. · Direzione Operativa Infrastrutture Roma', text: { it: 'Guida la Struttura di Ingegneria Civile con circa 100 risorse, realizzando circa 1 miliardo di euro di investimenti: prima parte del nuovo Anello Ferroviario di Roma, adeguamento a categoria di carico D4 del Nodo di Roma con 38 nuovi ponti e certificazione a sagoma PC80 del corridoio TEN-T Scandinavia–Mediterraneo sulla Chiarone–Roma Casilina. Progetta, realizza e attiva infrastruttura civile e nuovi impianti di armamento, garantendo l’integrazione con gli impianti tecnologici. È soggetto attuatore RFI per Roma–Lido, Anello Ferroviario di Roma, lavori Giubileo e Priverno–Terracina. Realizza interventi di sicurezza tecnologica e civile in 16 gallerie nell’ambito di oltre 20 interventi complessivi, definisce il piano territoriale di mitigazione sismica e del dissesto idrogeologico e verifica tecnicamente l’infrastruttura per trasporti eccezionali e nuovi rotabili.', en: 'Led the Civil Engineering unit with approximately 100 people and delivered about €1 billion of investment: the first section of the new Rome Railway Ring, D4 load-category upgrading of the Rome node with 38 new bridges, and PC80 gauge certification of the Scandinavian–Mediterranean TEN-T corridor on the Chiarone–Roma Casilina route. Designed, delivered and commissioned civil infrastructure and new trackwork systems, integrating them with technological systems. Served as RFI implementing authority for Roma–Lido, Rome Railway Ring, Jubilee works and Priverno–Terracina. Delivered technological and civil safety upgrades in 16 tunnels within more than 20 tunnel interventions, defined the territorial seismic and hydrogeological mitigation plan, and technically assessed infrastructure for exceptional loads and new rolling stock.' } },
  { years: 'Mar 2016 — Nov 2017', role: { it: 'Responsabile Opere Civili, Fabbricati e Impianti Speciali', en: 'Head of Civil Works, Buildings and Special Systems' }, org: 'RFI S.p.A. · Direzione Territoriale Produzione Roma', text: { it: 'Coordina progettazione e lavori della nuova linea Vigna Clara–Valle Aurelia in ambito civile, tecnologico e stazioni. Progetta upgrade sui corridoi TEN-T Chiarone–Roma Casilina e Roma–Napoli via Cassino. Realizza stazioni di Vigna Clara, Roma–Nettuno, Roccasecca–Avezzano e Civitavecchia Porto, con armamento e pensiline per sagome High Cube. Definisce il piano annuale dei lavori, istituisce uffici di direzione lavori e strumenti contrattuali per gli accordi quadro di settore e fornisce consulenza specialistica in infrastruttura civile e impianti tecnologici.', en: 'Coordinated design and construction of the Vigna Clara–Valle Aurelia railway line across civil works, technology and stations. Designed TEN-T upgrades on Chiarone–Roma Casilina and Rome–Naples via Cassino. Delivered stations at Vigna Clara, on the Rome–Nettuno and Roccasecca–Avezzano lines, and Civitavecchia Porto, including trackwork and High Cube clearance canopies. Defined annual work plans, established construction supervision offices and framework-contract tools, and provided specialist advice on civil infrastructure and technological systems.' } },
  { years: 'Mag 2014 — Feb 2016', role: { it: 'Responsabile U.O. Team Sviluppo Locale Opere Civili', en: 'Head of Local Development Civil Works Unit' }, org: 'RFI S.p.A. · Direzione Territoriale Produzione Roma', text: { it: 'Guida lavori di armamento nei PRG di Roma Tiburtina, Casilina, Scalo San Lorenzo e Campo Leone. Progetta e realizza armamento e trazione elettrica per i raccordi ferroviari Overail, Piemonte, Interporto di Orte, Interporto della Marsica e Raccordo Plasser e Mattia C. Riprogetta dal punto di vista aerodinamico 56 km di barriere antirumore sulla AV Roma–Napoli. Guida il Team di Controllo Opere d’Arte, conduce analisi di rischio per l’esercizio in sotterraneo e analisi di vulnerabilità sismica di ponti e fabbricati, e presidia capital budgeting e project management per potenziamento e upgrading delle linee.', en: 'Led trackwork in station layouts at Roma Tiburtina, Casilina, Scalo San Lorenzo and Campo Leone. Designed and delivered trackwork and electric traction for the Overail, Piemonte, Interporto di Orte, Interporto della Marsica and Plasser e Mattia C. railway sidings. Aerodynamically redesigned 56 km of noise barriers on the Rome–Naples high-speed line. Led the Structural Assets Control Team, carried out underground operating-risk and seismic-vulnerability analyses for bridges and buildings, and oversaw capital budgeting and project management for line upgrading works.' } },
  { years: 'Mag 2011 — Apr 2014', role: { it: 'Assistente Project Manager e Referente Task Force Sicurezza nelle Gallerie', en: 'Assistant Project Manager and Tunnel Safety Task Force Representative' }, org: 'RFI S.p.A. · Direzione Territoriale Produzione Roma', text: { it: 'Dirige lavori civili e tecnologici in molteplici cantieri, coordina la sicurezza CSP/CSE ai sensi del D.Lgs. 81/08 per interventi fino a 15 milioni di euro, gestisce relazioni con enti pubblici e stakeholder chiave nei progetti strategici e conduce analisi di rischio e vulnerabilità sismica di ponti e fabbricati.', en: 'Directed civil and technological works on multiple construction sites, coordinated CSP/CSE safety under Italian Legislative Decree 81/08 for projects up to €15 million, managed relationships with public authorities and key stakeholders on strategic investments, and carried out risk and seismic-vulnerability analyses for bridges and buildings.' } },
  { years: 'Mag 2009 — Apr 2011', role: { it: 'Referente Pianificazione Industriale e Monitoraggio KPI – Business Immobiliare e Trasporto', en: 'Industrial Planning & KPI Monitoring – Real Estate and Transport Business' }, org: 'Ferrovie dello Stato Italiane S.p.A. · Direzione Centrale Strategie e Pianificazione', text: { it: 'Consolida la pianificazione industriale delle società del Gruppo FS nel Real Estate (Grandi Stazioni, Cento Stazioni, Sistemi Urbani, Ferservizi); supporta i vertici nelle operazioni straordinarie verificando la congruità dei Business Plan e contribuendo alle acquisizioni di Arriva Deutschland (Netinera) e PKP Cargo. Analizza i mercati europeo e nazionale del trasporto passeggeri, merci e logistica, oltre a mercato e finanza immobiliare. Definisce e monitora KPI per strategie di business e tecnologie emergenti e rappresenta FS nei gruppi UIC Financial Indicators e UIC Statistics.', en: 'Consolidated industrial planning for FS Group real-estate companies (Grandi Stazioni, Cento Stazioni, Sistemi Urbani, Ferservizi); supported senior management in extraordinary transactions by assessing business plans and contributing to the Arriva Deutschland (Netinera) and PKP Cargo acquisitions. Analysed European and Italian passenger, freight and logistics markets as well as the Italian real-estate market and finance. Defined and monitored Group business KPIs and emerging technologies and represented FS in UIC Financial Indicators and UIC Statistics working groups.' } },
  { years: 'Nov 2006 — Apr 2009', role: { it: 'Ingegnere di Progetto – Opere Civili, Strutture in Sotterraneo e Sicurezza', en: 'Project Engineer – Civil Works, Underground Structures and Safety' }, org: 'RFI S.p.A. · Direzione Tecnica, Ingegneria Civile', text: { it: 'Rappresenta RFI presso AEIF, CEN, UIC e FIT su Safety in Railway Tunnels, manutenzione gallerie, ventilazione fumi e materiale rotabile convenzionale, contribuendo alle TSI. È membro del Comitato di Coordinamento delle gallerie transfrontaliere Brenner Basis Tunnel e Torino–Lione per aspetti statico-strutturali, fire engineering e sicurezza dell’esercizio in sotterraneo. Come Organismo di Ispezione di Tipo B effettua verifiche di appaltabilità per progetti superiori a 20 milioni di euro, conduce sperimentazioni di aerodinamica dei treni AV in galleria e valuta l’impatto tecnico-economico di nuove tecnologie.', en: 'Represented RFI at AEIF, CEN, UIC and FIT on Safety in Railway Tunnels, tunnel maintenance, smoke ventilation and conventional rolling stock, contributing to TSI development. Served on the Coordination Committee for the Brenner Base Tunnel and Turin–Lyon cross-border tunnels on structural, fire-engineering and underground-operational-safety matters. As a Type B Inspection Body, performed tenderability reviews for projects above €20 million, conducted high-speed train tunnel-aerodynamics testing and assessed the technical-economic impact of new technologies.' } },
  { years: 'Apr 2002 — Ott 2006', role: { it: 'Ingegnere di Progetto – Progettazione e Pianificazione Infrastrutture', en: 'Project Engineer – Infrastructure Design and Planning' }, org: 'RFI S.p.A. · Direzione Investimenti', text: { it: 'Introduce procedure sistematizzate per diagnosi, monitoraggio, manutenzione e calcolo delle strutture civili in sotterraneo e modelli prestazionali per la valutazione dei livelli di rischio dell’esercizio ferroviario in galleria. Gestisce progetti di innovazione tecnologica della rete, tra cui i sistemi di manutenzione automatizzata delle opere d’arte on condition Radiis e Domus; introduce modelli di progettazione condivisi nei gruppi di studio europei, verifica la conformità delle dotazioni di sicurezza nelle gallerie AV Roma–Napoli e Torino–Novara e redige dossier di valutazione economico-finanziaria per il Comitato Investimenti.', en: 'Introduced systematic procedures for diagnosis, monitoring, maintenance and calculation of underground civil structures and performance-based models for railway tunnel operating risk. Managed network-technology innovation projects, including the Radiis and Domus automated condition-based structural monitoring systems; introduced design models shared in European study groups, assessed safety-equipment compliance in the Rome–Naples and Turin–Novara high-speed tunnels, and prepared economic-financial investment dossiers for the Investment Committee.' } },
  { years: 'Apr 2001 — Apr 2002', role: { it: 'Ingegnere di Progetto', en: 'Project Engineer' }, org: 'DMS Engineering S.r.l. · Progettazione Geotecnica e Strutturale', text: { it: 'Responsabile della progettazione geotecnica e strutturale di opere in superficie e in sotterraneo di tipo stradale, ferroviario e civile.', en: 'Responsible for geotechnical and structural design of road, railway and civil works, both surface and underground.' } },
  { years: 'Lug 2000 — Apr 2001', role: { it: 'Ingegnere – Area Tecnico-Patrimoniale', en: 'Engineer – Technical Property Area' }, org: 'Azienda U.S.L. Latina · Latina', text: { it: 'Cura le valutazioni di sicurezza statica degli asset immobiliari dell’Azienda.', en: 'Performed structural safety assessments of the organisation real-estate assets.' } },
]

const expertise: Copy[] = [
  { it: 'Ingegneria civile applicata alle infrastrutture ferroviarie', en: 'Civil engineering for railway infrastructure' }, { it: 'Opere in sotterraneo, gallerie e armamento', en: 'Underground works, tunnels and trackwork' }, { it: 'Fire Engineering e sicurezza antincendio in galleria', en: 'Fire engineering and tunnel fire safety' }, { it: 'Aerodinamica gallerie e treni Alta Velocità', en: 'Tunnel aerodynamics and high-speed trains' }, { it: 'Risk analysis, mitigazione sismica e idrogeologica', en: 'Risk analysis, seismic and hydrogeological mitigation' }, { it: 'Specifiche Tecniche di Interoperabilità (TSI) e normativa UE', en: 'Technical Specifications for Interoperability (TSI) and EU regulation' }, { it: 'Project & Construction Management', en: 'Project & Construction Management' }, { it: 'Capital budgeting e valutazioni economico-finanziarie degli investimenti', en: 'Capital budgeting and economic-financial investment appraisal' }, { it: 'Pianificazione e controllo costi / tempi / qualità', en: 'Cost, schedule and quality planning and control' }, { it: 'Coordinamento sicurezza cantieri (D.Lgs. 81/08 – CSP/CSE)', en: 'Construction-site safety coordination' }, { it: 'Collaudo statico e verifiche tecnico-amministrative (CTA)', en: 'Structural testing and technical-administrative inspection' }, { it: 'Leadership di team eterogenei fino a circa 100 persone in 5 dipartimenti', en: 'Leadership of heterogeneous teams up to approximately 100 people across 5 departments' },
]

const areas: Copy[] = [
  { it: 'Ponti e opere d’arte ferroviarie', en: 'Railway bridges and civil structures' }, { it: 'Gallerie, sicurezza e fire engineering', en: 'Tunnels, safety and fire engineering' }, { it: 'Armamento, stazioni e impianti speciali', en: 'Trackwork, stations and special systems' }, { it: 'Corridoi TEN-T e interoperabilità', en: 'TEN-T corridors and interoperability' }, { it: 'Potenziamento, rinnovo e manutenzione della rete', en: 'Network upgrading, renewal and maintenance' }, { it: 'Strategia, investimenti e capital budgeting', en: 'Strategy, investments and capital budgeting' }, { it: 'Collaudi, verifiche e certificazioni tecniche', en: 'Testing, inspections and technical certification' }, { it: 'Standardizzazione e rappresentanza tecnica europea', en: 'European technical standardisation and representation' },
]

const results: Copy[] = [
  { it: '≈ 1 miliardo € · investimenti infrastrutturali realizzati 2017–2023', en: '≈ €1 billion · infrastructure investments delivered 2017–2023' }, { it: '38 · nuovi ponti per l’adeguamento D4 del Nodo di Roma', en: '38 · new bridges for Rome node D4 load-category upgrading' }, { it: 'PC80 · certificazione del corridoio TEN-T Scandinavia–Mediterraneo', en: 'PC80 · certification of the Scandinavian–Mediterranean TEN-T corridor' }, { it: '20+ · interventi complessivi in galleria', en: '20+ · tunnel interventions delivered' }, { it: '16 · gallerie con interventi di sicurezza tecnologica e civile', en: '16 · tunnels with technological and civil safety upgrades' }, { it: '≈ 100 · persone coordinate direttamente', en: '≈ 100 · people directly supervised' }, { it: '5 · dipartimenti coordinati', en: '5 · departments coordinated' }, { it: '24+ · anni di esperienza professionale', en: '24+ · years of professional experience' }, { it: '15 M€ · valore degli interventi fino al quale ha coordinato CSP/CSE', en: '€15m · projects up to this value under CSP/CSE safety coordination' }, { it: '56 km · barriere antirumore riprogettate sulla AV Roma–Napoli', en: '56 km · noise barriers redesigned on the Rome–Naples high-speed line' }, { it: '> 20 M€ · progetti verificati come Organismo di Ispezione di Tipo B', en: '> €20m · projects reviewed as a Type B Inspection Body' }, { it: '3 · edizioni del Master Sapienza: 2020, 2021, 2022', en: '3 · Sapienza Master editions: 2020, 2021, 2022' },
]

const diary: DiaryItem[] = [
  { image: 'varo-ponte-panoramica.webp', title: { it: 'Varo di ponte ferroviario', en: 'Railway bridge launch' }, text: { it: 'Panoramica di cantiere durante il varo di un nuovo ponte ferroviario.', en: 'Site overview during the launch of a new railway bridge.' } },
  { image: 'varo-ponte-collage.webp', title: { it: 'Sequenza di varo', en: 'Launch sequence' }, text: { it: 'Fasi successive di un’operazione di varo, dal montaggio allo scorrimento in opera.', en: 'Successive phases of a launch operation, from assembly to sliding into place.' } },
  { image: 'varo-ponte-verde-aereo.webp', title: { it: 'Ripresa aerea di varo', en: 'Aerial view of a bridge launch' }, text: { it: 'Inquadramento aereo dell’area di cantiere e dell’infrastruttura esistente.', en: 'Aerial framing of the construction site and the surrounding infrastructure.' } },
  { image: 'varo-ponte-notturno.webp', title: { it: 'Varo in finestra notturna', en: 'Night-window launch' }, text: { it: 'Operazioni condotte in interruzioni notturne per minimizzare l’impatto sull’esercizio.', en: 'Operations carried out in night possessions to minimise impact on operations.' } },
  { image: 'ponte-reticolare-collage-01.webp', title: { it: 'Ponte a travata reticolare in acciaio', en: 'Steel truss bridge' }, text: { it: 'Montaggio e varo di un’opera a travata reticolare in acciaio.', en: 'Assembly and launch of a steel truss bridge structure.' } },
  { image: 'ponte-reticolare-collage-02-ritratto.webp', title: { it: 'In cantiere sul ponte reticolare', en: 'On site at the truss bridge' }, text: { it: 'Sopralluogo tecnico in cantiere durante le fasi realizzative dell’opera.', en: 'Technical site inspection during the works.' } },
  { image: 'ponte-arco-restauro.webp', title: { it: 'Restauro di ponte ad arco', en: 'Arch bridge restoration' }, text: { it: 'Interventi di restauro e consolidamento su un’opera d’arte storica.', en: 'Restoration and consolidation works on a historic civil structure.' } },
  { image: 'demolizione-ponte-muratura-collage.webp', title: { it: 'Demolizione di ponte in muratura', en: 'Demolition of a masonry bridge' }, text: { it: 'Sequenza di demolizione controllata di un’opera in muratura a fine vita utile.', en: 'Controlled demolition sequence of a masonry structure at the end of its service life.' } },
  { image: 'demolizione-arco-muratura-collage.webp', title: { it: 'Demolizione di ponte ad arco in muratura', en: 'Demolition of a masonry arch bridge' }, text: { it: 'Rimozione di un’opera ad arco in muratura in vista della sua sostituzione.', en: 'Removal of a masonry arch structure ahead of its replacement.' } },
  { image: 'sottovia-aereo-scatolare.webp', title: { it: 'Sottovia scatolare, ripresa aerea', en: 'Box underpass, aerial view' }, text: { it: 'Inquadramento aereo di un nuovo sottovia scatolare in ambito ferroviario.', en: 'Aerial framing of a new box underpass beneath the railway.' } },
  { image: 'sottovia-collage-4foto.webp', title: { it: 'Realizzazione di un sottovia', en: 'Underpass construction' }, text: { it: 'Fasi di scavo, varo e completamento di un sottovia scatolare in cemento armato.', en: 'Excavation, launch and completion phases of a reinforced-concrete box underpass.' } },
  { image: 'scavo-sottovia-cilindri.webp', title: { it: 'Spingitubo per sottovia', en: 'Pipe-jacking for an underpass' }, text: { it: 'Tecnica di spinta di elementi cilindrici per la realizzazione di un sottovia in esercizio.', en: 'Pipe-jacking technique for constructing an underpass beneath an operating line.' } },
  { image: 'scatolare-coprem.webp', title: { it: 'Elemento scatolare prefabbricato', en: 'Precast box culvert element' }, text: { it: 'Posa di elementi scatolari prefabbricati per opere di attraversamento.', en: 'Installation of precast box culvert elements for crossing works.' } },
  { image: 'galleria-scavo-fresa.webp', title: { it: 'Scavo meccanizzato in galleria', en: 'Mechanised tunnel excavation' }, text: { it: 'Avanzamento dello scavo con fresa meccanizzata.', en: 'Excavation advance using a tunnel boring machine.' } },
  { image: 'galleria-interno-01.webp', title: { it: 'Interno galleria: rivestimento e sicurezza', en: 'Tunnel interior: lining and safety' }, text: { it: 'Interventi sul rivestimento e sulle dotazioni di sicurezza dell’esercizio in sotterraneo.', en: 'Works on the lining and safety equipment of underground operations.' } },
  { image: 'galleria-interno-02.webp', title: { it: 'Interno galleria: manutenzione', en: 'Tunnel interior: maintenance' }, text: { it: 'Attività di manutenzione e controllo delle strutture in sotterraneo.', en: 'Maintenance and structural monitoring activities underground.' } },
  { image: 'galleria-interno-scavo.webp', title: { it: 'Fronte di scavo in galleria', en: 'Tunnel excavation face' }, text: { it: 'Fase di avanzamento al fronte durante lo scavo in sotterraneo.', en: 'Face-advance phase during underground excavation.' } },
  { image: 'galleria-percorrenza.webp', title: { it: 'Percorrenza in galleria', en: 'Tunnel walkthrough' }, text: { it: 'Ispezione tecnica lungo lo sviluppo della galleria.', en: 'Technical inspection along the length of the tunnel.' } },
  { image: 'galleria-prima-dopo-collage.webp', title: { it: 'Galleria: prima e dopo l’intervento', en: 'Tunnel: before and after the works' }, text: { it: 'Confronto tra lo stato ante operam e post operam di un intervento in galleria.', en: 'Comparison between the pre- and post-intervention state of a tunnel upgrade.' } },
  { image: 'consolidamento-scarpata.webp', title: { it: 'Consolidamento di scarpata', en: 'Slope consolidation' }, text: { it: 'Interventi geotecnici di consolidamento e mitigazione del dissesto idrogeologico.', en: 'Geotechnical consolidation works and hydrogeological risk mitigation.' } },
  { image: 'scarpata-lanuvio.webp', title: { it: 'Scarpata di Lanuvio', en: 'Lanuvio slope' }, text: { it: 'Intervento di stabilizzazione su un versante in prossimità della linea ferroviaria.', en: 'Stabilisation works on a slope adjacent to the railway line.' } },
  { image: 'cantiere-urbano-01.webp', title: { it: 'Cantiere in ambito urbano', en: 'Urban construction site' }, text: { it: 'Gestione delle interferenze e della sicurezza in un cantiere ferroviario urbano.', en: 'Managing interfaces and safety on an urban railway construction site.' } },
  { image: 'cantiere-urbano-02.webp', title: { it: 'Opere civili in ambito urbano', en: 'Civil works in an urban setting' }, text: { it: 'Realizzazione di opere civili in un contesto urbano denso.', en: 'Delivery of civil works within a dense urban context.' } },
  { image: 'cantiere-impalcatura-verticale.webp', title: { it: 'Impalcatura verticale di cantiere', en: 'Vertical construction scaffolding' }, text: { it: 'Allestimento verticale del cantiere per interventi in quota.', en: 'Vertical site setup for works at height.' } },
  { image: 'scavo-notturno.webp', title: { it: 'Scavo in finestra notturna', en: 'Night-window excavation' }, text: { it: 'Attività di scavo condotte in interruzioni notturne programmate.', en: 'Excavation works carried out during planned night possessions.' } },
  { image: 'muro-sostegno-dettaglio.webp', title: { it: 'Muro di sostegno, dettaglio costruttivo', en: 'Retaining wall, construction detail' }, text: { it: 'Dettaglio costruttivo di un muro di sostegno lungo la linea.', en: 'Construction detail of a retaining wall along the line.' } },
  { image: 'viadotto-storico-panoramica.webp', title: { it: 'Viadotto storico', en: 'Historic viaduct' }, text: { it: 'Vista panoramica di un viadotto storico in esercizio.', en: 'Panoramic view of a historic viaduct in operation.' } },
]

const videos: VideoItem[] = [
  { id: '5TOuHte0nSo', title: { it: 'Varo trasversale di ponte a travata reticolare in acciaio', en: 'Transversal launch of a steel truss bridge' }, caption: { it: 'Sequenza di varo trasversale di un ponte ferroviario di 30 m a travata reticolare.', en: 'Transversal launch sequence of a 30 m steel truss railway bridge.' } },
  { id: '2ERIls-N5FA', title: { it: 'Varo di un cavalcavia in acciaio a travi estradossate', en: 'Launch of a 40 m extradosed steel road bridge' }, caption: { it: 'Il varo di un cavalcavia in acciaio a travi estradossate di 40 m.', en: 'Launching of a 40 m steel road bridge with extradosed beams.' } },
  { id: '85ZxUrBjsJ4', title: { it: 'Dal ponte ad arco in muratura al sottovia scatolare', en: 'From masonry arch bridge to box underpass' }, caption: { it: 'Dal ponte ad arco in muratura al sottovia scatolare in cls.', en: 'From the masonry arched bridge to the concrete box underpass.' } },
  { id: 'mBXq7QyqAXU', title: { it: 'Varo trasversale di ponte in acciaio', en: 'Transversal launch of a steel bridge' }, caption: { it: 'Esempio di varo trasversale di ponte in acciaio.', en: 'Example of transversal launch of a steel bridge.' } },
  { id: 'v2K7CxV0buU', title: { it: 'Varo di un nuovo ponte a travi in acciaio', en: 'Launch of a new steel-beam bridge' }, caption: { it: 'Varo di un nuovo ponte a travi in acciaio incorporate.', en: 'Launch of a new bridge with incorporated steel beams.' } },
  { id: 'y5gCqsuNTRI', title: { it: 'Realizzazione e varo del ponte in acciaio Zambra', en: 'Construction and launch of the Zambra steel bridge' }, caption: { it: 'Realizzazione e varo del ponte in acciaio Zambra · 2021.', en: 'Construction and launch of the Zambra steel bridge · 2021.' } },
  { id: 'R-oy8_PSvvI', title: { it: 'Rimozione di ponte pedonale in cemento armato', en: 'Removal of a concrete footbridge' }, caption: { it: 'Rimozione di ponte pedonale in cls.', en: 'Removal of a reinforced-concrete footbridge.' } },
  { id: 'fKNXOBJ8XFk', title: { it: 'Rimozione di ponte imbarco in acciaio', en: 'Removal of a steel loading bridge' }, caption: { it: 'Esempio di rimozione di ponte imbarco in acciaio.', en: 'Example of removal of a steel loading bridge.' } },
  { id: 'PRV1iSJicgQ', title: { it: 'Rimozione di un ponte ferroviario', en: 'Removal of a railway bridge' }, caption: { it: 'La rimozione di un ponte ferroviario.', en: 'Removal of a railway bridge.' } },
  { id: '02Gk13v8u_Q', title: { it: 'Passerella pedonale provvisoria in acciaio', en: 'Temporary steel footbridge' }, caption: { it: 'Realizzazione e rimozione passerella pedonale provvisoria in acciaio · 2021.', en: 'Construction and removal of a temporary steel footbridge · 2021.' } },
  { id: 'Qyi8eGPJpsE', title: { it: 'Ponte ad arco reticolare in acciaio a tre cerniere', en: 'Three-hinged steel lattice arch bridge' }, caption: { it: 'Esempio di ponte ad arco reticolare in acciaio a tre cerniere.', en: 'Example of a three-hinged steel lattice arch bridge.' } },
]

const education: EducationItem[] = [
  { years: '2006 — 2007', title: { it: 'Executive Master in General Management', en: 'Executive Master in General Management' }, org: { it: 'LUISS Business School', en: 'LUISS Business School' }, detail: { it: 'Pianificazione Strategica e Organizzazione Aziendale, Amministrazione e Controllo di Gestione, Finanza, Strategie e Politiche di Marketing, Gestione delle Operations, Gestione HR.', en: 'Strategic planning and organisational design, management accounting and control, finance, marketing strategy and policy, operations management, HR management.' } },
  { years: '1999 — 2000', title: { it: 'Laurea in Ingegneria Civile (indirizzo Geotecnica) — 110/110 e Lode', en: 'Degree in Civil Engineering (Geotechnical) — 110/110 cum laude' }, org: { it: 'Università “La Sapienza” di Roma', en: 'Sapienza University of Rome' }, detail: { it: 'Premio di Laurea del Ministro delle Infrastrutture P. Lunardi.', en: 'Awarded the Degree Prize by the Minister of Infrastructure P. Lunardi.' } },
  { years: '2001', title: { it: 'Abilitazione alla professione di Ingegnere', en: 'Professional Engineering licence' }, org: { it: 'Ordine degli Ingegneri di Roma', en: 'Rome Order of Engineers' }, detail: { it: 'Iscritto all’Albo degli Ingegneri di Roma, n. 31957.', en: 'Registered with the Rome Order of Engineers, no. 31957.' } },
]

const documents: DiaryItem[] = [
  { image: 'diploma-societa-italiana-gallerie-2001.webp', title: { it: 'Diploma, 1° Premio Nazionale SIG · 2001', en: 'Diploma, 1st National SIG Award · 2001' }, text: { it: '', en: '' } },
  { image: 'lettera-premio-cifi-2011.webp', title: { it: 'Lettera di assegnazione, Premio CIFI · 2011', en: 'Award letter, CIFI Prize · 2011' }, text: { it: '', en: '' } },
  { image: 'lettera-cifi-e-copertina-tp.webp', title: { it: 'Lettera CIFI e copertina Tecnica Professionale', en: 'CIFI letter and Tecnica Professionale cover' }, text: { it: '', en: '' } },
  { image: 'collage-premiazione-cifi-2011.webp', title: { it: 'Cerimonia di premiazione CIFI · 2011', en: 'CIFI award ceremony · 2011' }, text: { it: '', en: '' } },
  { image: 'premiazione-gruppo.webp', title: { it: 'Cerimonia di premiazione, foto di gruppo', en: 'Award ceremony, group photo' }, text: { it: '', en: '' } },
  { image: 'premiazione-e-botti.webp', title: { it: 'Cerimonia di premiazione', en: 'Award ceremony' }, text: { it: '', en: '' } },
]

const publications: PublicationItem[] = [
  { group: '01', year: '2009', title: 'La Normativa europea per la sicurezza delle gallerie', source: 'Tecnica Professionale n. 3/09, CIFI · marzo 2009' }, { group: '01', year: '2007', title: 'Modernizzazione e competitività del Paese attraverso il rilancio del trasporto ferroviario', source: 'Notizie Speciale Ferrovie – Federmanager · maggio 2007', cover: 'articolo-speciale-ferrovie-2007.webp' }, { group: '01', year: '2006', title: 'Fenomeni aerodinamici indotti dal transito dei treni AV', source: 'Ingegneria Ferroviaria, CIFI · ottobre 2006' }, { group: '02', year: '2006', title: 'Fire Safe Design for Rail Tunnels', source: 'European Community 5th Framework Programme · maggio 2006' }, { group: '02', year: '2005', title: 'Regulation Guidelines for Fire Safe Design in Rail Tunnels', source: 'European Community 5th Framework Programme · febbraio 2005' }, { group: '03', year: '2003', title: 'L’evoluzione del concetto di sicurezza nelle gallerie ferroviarie', source: 'Tecnica Professionale n. 9/03 · settembre 2003', cover: 'cover-tecnica-professionale-2003.webp' }, { group: '03', year: '2001', title: 'Analisi ad elementi distinti di cavità sotterranee in ammassi rocciosi stratificati', source: 'Gallerie e Grandi Opere in Sotterraneo n. 65, Ed. Patron · dicembre 2001', cover: 'cover-gallerie-magazine.webp' },
]

function App() {
  const [lang, setLang] = useState<Lang>('it')
  const t = (x: Copy) => x[lang]
  return <div className="site-shell">
    <header className="site-header"><a className="brand" href="#top"><span className="brand-mark">GM</span><span>Giorgio Micolitti</span></a><nav><a href="#profile">{lang === 'it' ? 'Profilo' : 'Profile'}</a><a href="#rfi">25 anni RFI</a><a href="#expertise">{lang === 'it' ? 'Competenze' : 'Expertise'}</a><a href="#areas">{lang === 'it' ? 'Aree' : 'Areas'}</a><a href="#results">{lang === 'it' ? 'Risultati' : 'Results'}</a><a href="#bridge">Ponte</a><a href="#diary">Project diary</a><a href="#videos">{lang === 'it' ? 'Video' : 'Videos'}</a><a href="#august-2022">Agosto 2022</a><a href="#teaching">{lang === 'it' ? 'Docenza' : 'Teaching'}</a><a href="#education">{lang === 'it' ? 'Formazione' : 'Education'}</a><div className="pub-nav"><a href="#publications">{lang === 'it' ? 'Pubblicazioni' : 'Publications'}</a><span><a href="#pub-01">01</a> · <a href="#pub-02">02</a> · <a href="#pub-03">03</a></span></div></nav><div className="lang"><button className={lang === 'it' ? 'active' : ''} onClick={() => setLang('it')}>IT</button><span>/</span><button className={lang === 'en' ? 'active' : ''} onClick={() => setLang('en')}>EN</button></div></header>
    <main id="top">
      <section className="hero dark"><div className="wrap hero-grid"><div><p className="kicker">CIVIL ENGINEERING · RAILWAY INFRASTRUCTURE</p><h1>Civil Engineering Works,<br/>Infrastructure Constructions,<br/>Tunnels &amp; Safety</h1><p className="hero-sub">Sustainability challenges in a constantly evolving framework</p><p className="hero-name">Giorgio Micolitti</p></div><Portrait/></div></section>
      <section id="profile" className="light"><div className="wrap section-head"><p className="kicker">01 · {lang === 'it' ? 'PROFILO PROFESSIONALE' : 'PROFESSIONAL PROFILE'}</p><h2>{lang === 'it' ? 'Profilo professionale completo' : 'Full professional profile'}</h2></div><div className="wrap profile-grid"><div className="profile-copy">{profile.map((p,i)=><p key={i}>{t(p)}</p>)}</div><aside className="profile-aside"><h3>{lang === 'it' ? 'Esperienza professionale' : 'Professional experience'}</h3>{experience.map((e,i)=><article className="experience-item" key={i}><span>{e.years}</span><h4>{t(e.role)}</h4><strong>{e.org}</strong><p>{t(e.text)}</p></article>)}<div className="mini-section"><h3>{lang === 'it' ? 'Collaudi e Certificazioni Tecniche' : 'Testing and Technical Certifications'}</h3><p>{lang === 'it' ? 'Collaudatore Statico e Direttore CTA (Certificato di Collaudo Tecnico-Amministrativo) per numerosi interventi infrastrutturali RFI realizzati tra il 2014 e il 2021, tra cui: sostituzione e realizzazione di travate metalliche e ponti sulle linee Roma–Grosseto e Roma–Formia; sottopassi, rampe, scale e adeguamento marciapiedi nella stazione di Aprilia; prolungamento pensiline e opere strutturali a Roma Tiburtina; opere civili per l’accessibilità del fascio Air Terminal di Roma Ostiense (servizio NTV); rinnovamento deviatoi sulle linee Roma–Viterbo, Roma–Grosseto e Roma–Formia; riqualificazione e adeguamento al brand delle stazioni nell’ambito dei progetti Easy/Smart Station e Wi-Fi Station (Cava dei Tirreni).' : 'Structural Tester and CTA Director for numerous RFI infrastructure works delivered between 2014 and 2021, including: replacement and construction of steel spans and bridges on the Roma–Grosseto and Roma–Formia lines; underpasses, ramps, stairs and platform upgrades at Aprilia station; canopy extensions and structural works at Roma Tiburtina; accessibility works for the Air Terminal complex at Roma Ostiense (NTV service); turnout renewals on the Roma–Viterbo, Roma–Grosseto and Roma–Formia lines; rebranding and upgrading of stations under the Easy/Smart Station and Wi-Fi Station programmes (Cava dei Tirreni).'}</p></div><div className="mini-section"><h3>{lang === 'it' ? 'Lingue' : 'Languages'}</h3><p>{lang === 'it' ? 'Italiano — madrelingua · Inglese — scritto e parlato: ottimo · Francese — buono' : 'Italian — native · English — excellent written and spoken · French — good'}</p></div></aside></div></section>
      <section id="rfi" className="editorial dark"><div className="wrap editorial-grid"><div><p className="kicker">02 · 25 ANNI DI RFI</p><h2>{lang === 'it' ? 'Un’esperienza progressivamente estesa.' : 'An experience progressively broadened over time.'}</h2></div><div><p className="lead">{lang === 'it' ? 'Dalla pianificazione infrastrutturale e dagli standard tecnici e normativi, alla strategia e valutazione degli investimenti, fino alla gestione operativa, manutenzione e realizzazione delle opere.' : 'From infrastructure planning and technical standards to strategy and investment appraisal, and then to operational management, maintenance and delivery of works.'}</p><p>{lang === 'it' ? 'Dal 2002 il percorso in RFI e nel Gruppo FS ha attraversato Direzione Investimenti, Direzione Tecnica, Direzione Centrale Strategie e Pianificazione e Direzione Operativa Territoriale di Roma, fino all’attuale responsabilità in Stretto di Messina S.p.A.' : 'Since 2002, the career within RFI and the FS Group has spanned Investment, Technical, Central Strategy & Planning and Rome Territorial Operations directorates, leading to the current responsibility at Stretto di Messina S.p.A.'}</p><div className="video-embed"><VideoPlayer id="9LUx1LBOJzA" title="25 anni di RFI"/><p className="video-caption">{lang === 'it' ? '25 anni di RFI — Una storia di persone, infrastrutture e responsabilità.' : 'Twenty-five years at RFI — a story of people, infrastructure and responsibility.'}</p></div></div></div></section>
      <section id="expertise" className="light"><div className="wrap section-head"><p className="kicker">03 · {lang === 'it' ? 'COMPETENZE' : 'EXPERTISE'}</p><h2>{lang === 'it' ? 'Competenze tecniche e manageriali' : 'Technical and management capabilities'}</h2></div><div className="wrap two-col-list">{expertise.map((x,i)=><div key={i}><span>{String(i+1).padStart(2,'0')}</span><p>{t(x)}</p></div>)}</div></section>
      <section id="areas" className="slate"><div className="wrap section-head"><p className="kicker">04 · {lang === 'it' ? 'AREE DI ATTIVITÀ' : 'AREAS OF ACTIVITY'}</p><h2>{lang === 'it' ? 'Infrastrutture, sistemi, processi' : 'Infrastructure, systems, processes'}</h2></div><div className="wrap areas-grid">{areas.map((x,i)=><article key={i}><span>{String(i+1).padStart(2,'0')}</span><h3>{t(x)}</h3></article>)}</div></section>
      <section id="results" className="light"><div className="wrap section-head"><p className="kicker">05 · {lang === 'it' ? 'RISULTATI CHIAVE' : 'KEY RESULTS'}</p><h2>{lang === 'it' ? 'Numeri che descrivono la scala delle responsabilità' : 'Numbers that describe the scale of responsibility'}</h2></div><div className="wrap results-grid">{results.map((x,i)=><article key={i}><span>{String(i+1).padStart(2,'0')}</span><p>{t(x)}</p></article>)}</div></section>
      <section id="bridge" className="bridge dark"><div className="wrap bridge-grid"><div><p className="kicker">06 · PONTE SULLO STRETTO</p><h2>{lang === 'it' ? 'Collegamenti ferroviari del Ponte sullo Stretto' : 'Railway connections to the Strait of Messina Bridge'}</h2></div><div><p className="lead">{lang === 'it' ? 'Dal novembre 2023 Giorgio Micolitti è Responsabile Ingegneria Collegamenti Ferroviari di Stretto di Messina S.p.A. e guida la relativa Struttura Organizzativa.' : 'Since November 2023, Giorgio Micolitti has served as Head of Railway Connections Engineering at Stretto di Messina S.p.A., leading the related organisational unit.'}</p><p>{lang === 'it' ? 'La sezione mantiene volutamente separati ruolo professionale e documentazione fotografica: vengono utilizzate soltanto immagini con attribuzione certa.' : 'The section deliberately keeps professional role and photographic documentation distinct: only imagery with certain attribution is used.'}</p></div></div><div className="wrap bridge-videos"><div className="video-embed"><VideoPlayer id="8hU4DBr4O5s" title="Ponte sullo Stretto di Messina — Collegamenti Ferroviari"/><p className="video-caption">{lang === 'it' ? 'Ponte sullo Stretto di Messina: Collegamenti Ferroviari a terra e effetti sulle preesistenze. Messina, 29 ottobre 2024.' : 'Strait of Messina Bridge: land-side railway connections and effects on existing assets. Messina, 29 October 2024.'}</p></div><div className="video-embed"><VideoPlayer id="iwm4JwfobGA" title="Esplorando il Futuro dei Collegamenti Ferroviari al Ponte sullo Stretto"/><p className="video-caption">{lang === 'it' ? 'Esplorando il Futuro dei Collegamenti Ferroviari al Ponte sullo Stretto di Messina. Messina, 18 marzo 2024.' : 'Exploring the Future of Railway Connections to the Strait of Messina Bridge. Messina, 18 March 2024.'}</p></div></div></section>
      <section id="diary" className="light"><div className="wrap section-head"><p className="kicker">07 · PROJECT DIARY</p><h2>{lang === 'it' ? 'Opere e cantieri in sequenza editoriale' : 'Works and construction sites in an editorial sequence'}</h2></div><div className="wrap diary">{diary.map((d,i)=><article className={i%2 ? 'diary-row reverse' : 'diary-row'} key={d.image}><div className="diary-copy"><span>{String(i+1).padStart(2,'0')}</span><h3>{t(d.title)}</h3><p>{t(d.text)}</p></div><figure><img src={`./images/${d.image}`} alt={t(d.title)}/><figcaption>{d.title.it}<em>{d.title.en}</em></figcaption></figure></article>)}</div></section>
      <section id="videos" className="dark"><div className="wrap section-head"><p className="kicker">08 · {lang === 'it' ? 'VIDEO & INSIGHTS' : 'VIDEO & INSIGHTS'}</p><h2>{lang === 'it' ? 'Vari, rimozioni e opere civili in sequenza' : 'Launches, removals and civil works in sequence'}</h2></div><div className="wrap video-grid">{videos.map(v=><article className="video-card" key={v.id}><VideoPlayer id={v.id} title={t(v.title)}/><h3>{t(v.title)}</h3><p>{v.caption.it}<em>{v.caption.en}</em></p></article>)}</div></section>
      <section id="august-2022" className="editorial slate"><div className="wrap editorial-grid"><div><p className="kicker">09 · AGOSTO 2022</p><h2>{lang === 'it' ? 'Il suono di due treni su un’opera appena realizzata' : 'The sound of two trains on a newly completed civil work'}</h2></div><div><p className="lead">{lang === 'it' ? 'Uno dei lavori estivi eseguiti dalla squadra di Ingegneria Civile della DOIT Roma, in finestre operative complesse e programmate nei mesi di minore traffico.' : 'One of the summer works delivered by the DOIT Rome Civil Engineering team within complex possessions planned during lower-traffic periods.'}</p><div className="video-embed"><VideoPlayer id="B2XEBK2oEao" title="Agosto 2022"/></div></div></div></section>
      <section id="teaching" className="light"><div className="wrap teaching-grid"><div><p className="kicker">10 · {lang === 'it' ? 'DOCENZA' : 'TEACHING'}</p><h2>Sapienza<br/>Università di Roma</h2></div><div><p className="lead">{lang === 'it' ? 'Docente di Tecnica dei Cantieri Infrastrutturali presso il Master Sapienza in Ingegneria delle Infrastrutture e dei Sistemi Ferroviari (IIS), edizioni 2020, 2021 e 2022.' : 'Lecturer in Infrastructure Construction Site Techniques within Sapienza University Master in Infrastructure and Railway Systems Engineering (IIS), editions 2020, 2021 and 2022.'}</p><div className="video-embed"><VideoPlayer id="VoLegEc26A8" title="Lezione Master IIS"/><p className="video-caption">{lang === 'it' ? 'Lezione Master IIS del 10.06.2022 — Master Università Sapienza di Roma, Ingegneria delle Infrastrutture e dei Sistemi Ferroviari, ed. 2022.' : 'Master IIS lecture, 10 June 2022 — Sapienza University of Rome Master in Infrastructure and Railway Systems Engineering, 2022 edition.'}</p></div></div></div></section>
      <section id="education" className="ivory"><div className="wrap section-head"><p className="kicker">11 · {lang === 'it' ? 'FORMAZIONE' : 'EDUCATION'}</p><h2>{lang === 'it' ? 'Percorso accademico e abilitazione professionale' : 'Academic background and professional licence'}</h2></div><div className="wrap education-list">{education.map((e,i)=><article className="experience-item" key={i}><span>{e.years}</span><h4>{t(e.title)}</h4><strong>{t(e.org)}</strong><p>{t(e.detail)}</p></article>)}</div></section>
      <section id="publications" className="publications ivory"><div className="wrap section-head"><p className="kicker">12 · {lang === 'it' ? 'PUBBLICAZIONI SELEZIONATE' : 'SELECTED PUBLICATIONS'}</p><h2>{lang === 'it' ? 'Ricerca, sicurezza, normativa e geotecnica' : 'Research, safety, regulation and geotechnics'}</h2></div>{(['01','02','03'] as const).map(group=><div id={`pub-${group}`} className="wrap pub-group" key={group}><div className="pub-group-title">{group}</div><div>{publications.filter(p=>p.group===group).map((p,i)=><article className={p.cover ? 'pub-item has-cover' : 'pub-item'} key={`${group}-${i}`}><span>{p.year}</span>{p.cover && <img className="pub-cover" src={`./images/${p.cover}`} alt={p.title}/>}<div><h3>{p.title}</h3><p>{p.source}</p></div></article>)}</div></div>)}<div className="wrap awards"><h3>{lang === 'it' ? 'Premi e riconoscimenti' : 'Awards and recognition'}</h3><div><strong>2001</strong><span>{lang === 'it' ? '1° Premio Nazionale Società Italiana Gallerie — Ministero delle Infrastrutture e dei Trasporti' : '1st National Award, Società Italiana Gallerie — Ministry of Infrastructure and Transport'}</span></div><div><strong>2005</strong><span>1° Premio Nazionale CIFI — Collegio Ingegneri Ferroviari Italiani</span></div><div><strong>2008</strong><span>2° Premio Nazionale CIFI</span></div><div><strong>2011</strong><span>2° Premio Nazionale CIFI</span></div></div><div className="wrap documents">{documents.map((d,i)=><figure key={i}><img src={`./images/${d.image}`} alt={t(d.title)}/><figcaption>{d.title.it}<em>{d.title.en}</em></figcaption></figure>)}</div></section>
      <footer className="dark"><div className="wrap footer-grid"><div><strong>Giorgio Micolitti</strong><p>Civil &amp; Geotechnical Engineering · Railway Infrastructure</p></div><div><a href="mailto:giorgiomicol@gmail.com">giorgiomicol@gmail.com</a><a href="https://www.linkedin.com/in/giorgiomicolitti/" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div></footer>
    </main>
  </div>
}

export default App
